# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-02-03 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('user', 'text')]),
        ),
    ]
