# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2023-02-04 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_db', '0006_auto_20230204_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcall',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_call', to='chat_db.Bot'),
        ),
        migrations.AlterField(
            model_name='botcall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
